export default SynonymsSearch = {
  // General Business Terms
  business: [
    "company",
    "firm",
    "enterprise",
    "organization",
    "venture",
    "concern",
    "operation",
    "trade",
    "commerce",
    "industry",
    "establishment",
    "corporation",
    "partnership",
    "agency",
    "practice",
    "outfit",
    "startup",
    "shop",
    "store",
    "marketplace",
    "dealings",
    "merchandising",
    "calling",
    "occupation",
    "pursuit",
    "work",
    "profession",
    "métier",
    "employment",
  ], //[](https://www.merriam-webster.com/thesaurus/business)[](https://www.thesaurus.com/browse/business)[](https://english.stackexchange.com/questions/45570/what-term-to-use-instead-of-company-to-represent-well-a-company)
  company: [
    "business",
    "firm",
    "corporation",
    "enterprise",
    "organization",
    "venture",
    "concern",
    "group",
    "association",
    "consortium",
    "partnership",
    "agency",
    "cooperative",
    "startup",
    "practice",
    "syndicate",
    "franchise",
    "institution",
    "establishment",
    "outfit",
    "collective",
  ], //[](https://english.stackexchange.com/questions/45570/what-term-to-use-instead-of-company-to-represent-well-a-company)[](https://www.thesaurus.com/browse/company)
  industry: [
    "sector",
    "field",
    "trade",
    "business",
    "commerce",
    "manufacturing",
    "production",
    "market",
    "line",
    "craft",
    "profession",
    "service",
    "world",
    "activity",
    "effort",
    "labor",
    "work",
    "enterprise",
  ], //[](https://www.merriam-webster.com/thesaurus/industry)[](https://www.collinsdictionary.com/us/dictionary/english-thesaurus/industry)[](https://www.collinsdictionary.com/dictionary/english-thesaurus/industry)
  sector: [
    "industry",
    "field",
    "segment",
    "domain",
    "area",
    "branch",
    "division",
    "category",
    "zone",
    "region",
    "sphere",
    "market",
    "group",
    "type",
  ], //[](https://www.investopedia.com/ask/answers/05/industrysector.asp)[](https://www.merriam-webster.com/thesaurus/sector)[](https://www.thesaurus.com/browse/sectors)

  // Primary Sector (Extraction and Harvesting)
  agriculture: [
    "farming",
    "agribusiness",
    "cultivation",
    "horticulture",
    "ranching",
    "crop production",
    "livestock",
    "dairy",
    "aquaculture",
    "forestry",
    "agri",
  ], //[](https://www.investopedia.com/ask/answers/05/industrysector.asp)
  mining: [
    "extraction",
    "quarrying",
    "drilling",
    "ore processing",
    "mineral",
    "prospecting",
    "geology",
  ], //[](https://www.investopedia.com/ask/answers/05/industrysector.asp)

  // Secondary Sector (Manufacturing and Construction)
  manufacturing: [
    "production",
    "industry",
    "fabrication",
    "assembly",
    "processing",
    "industrial",
    "factory",
    "workshop",
    "plant",
    "crafting",
  ], //[](https://www.investopedia.com/ask/answers/05/industrysector.asp)[](https://www.collinsdictionary.com/us/dictionary/english-thesaurus/industry)
  construction: [
    "building",
    "development",
    "infrastructure",
    "erection",
    "civil engineering",
    "contracting",
    "real estate",
  ], //[](https://www.investopedia.com/ask/answers/05/industrysector.asp)

  // Tertiary Sector (Services)
  retail: [
    "shop",
    "store",
    "boutique",
    "market",
    "sales",
    "merchandising",
    "commerce",
    "dealership",
    "outlet",
    "e-commerce",
    "retailing",
  ], //[](https://www.merriam-webster.com/thesaurus/business)[](https://www.investopedia.com/ask/answers/05/industrysector.asp)
  hospitality: [
    "hotel",
    "inn",
    "lodge",
    "guesthouse",
    "resort",
    "motel",
    "hostel",
    "restaurant",
    "catering",
    "tourism",
    "accommodation",
    "service",
  ], //[](https://www.merriam-webster.com/thesaurus/business)
  restaurant: [
    "eatery",
    "diner",
    "bistro",
    "cafe",
    "kitchen",
    "canteen",
    "food service",
    "brasserie",
    "tavern",
    "pub",
    "grill",
  ], //[](https://www.merriam-webster.com/thesaurus/business)
  cafe: [
    "coffee shop",
    "bistro",
    "cafeteria",
    "espresso bar",
    "tea house",
    "diner",
    "patisserie",
    "bakery",
  ], // Original example
  healthcare: [
    "hospital",
    "clinic",
    "medical center",
    "health service",
    "practice",
    "pharmacy",
    "care",
    "wellness",
    "medical",
    "nursing",
    "therapy",
  ], //[](https://www.investopedia.com/ask/answers/05/industrysector.asp)[](https://www.merriam-webster.com/thesaurus/sector)
  education: [
    "school",
    "academy",
    "university",
    "college",
    "institute",
    "training",
    "learning",
    "teaching",
    "tutoring",
    "coaching",
    "seminary",
  ], //[](https://www.investopedia.com/ask/answers/05/industrysector.asp)
  transportation: [
    "logistics",
    "shipping",
    "freight",
    "transit",
    "delivery",
    "haulage",
    "trucking",
    "airlines",
    "railways",
    "courier",
    "mobility",
  ], //[](https://www.investopedia.com/ask/answers/05/industrysector.asp)
  entertainment: [
    "media",
    "film",
    "television",
    "music",
    "theater",
    "gaming",
    "events",
    "amusement",
    "recreation",
    "performance",
    "showbiz",
  ], //[](https://www.investopedia.com/ask/answers/05/industrysector.asp)[](https://www.thesaurus.com/browse/industries)
  finance: [
    "banking",
    "insurance",
    "investment",
    "brokerage",
    "wealth management",
    "financial services",
    "lending",
    "credit",
    "accounting",
    "fintech",
  ], //[](https://www.investopedia.com/ask/answers/05/industrysector.asp)

  // Quaternary Sector (Knowledge-Based)
  technology: [
    "tech",
    "software",
    "IT",
    "hardware",
    "digital",
    "innovation",
    "startup",
    "development",
    "coding",
    "systems",
    "tech industry",
    "fintech",
    "edtech",
    "healthtech",
  ], //[](https://www.investopedia.com/ask/answers/05/industrysector.asp)[](https://www.indeed.com/career-advice/career-development/business-buzzwords)
  consulting: [
    "advisory",
    "management",
    "strategy",
    "professional services",
    "counseling",
    "guidance",
    "expertise",
    "analysis",
    "solutions",
  ], //[](https://www.indeed.com/career-advice/career-development/business-buzzwords)
  research: [
    "development",
    "R&D",
    "innovation",
    "study",
    "analysis",
    "investigation",
    "science",
    "exploration",
    "lab",
  ], //[](https://www.merriam-webster.com/thesaurus/industry)

  // Descriptive Terms and Buzzwords
  innovative: [
    "cutting-edge",
    "advanced",
    "modern",
    "pioneering",
    "creative",
    "forward-thinking",
    "groundbreaking",
    "disruptive",
    "next-generation",
  ], //[](https://www.indeed.com/career-advice/career-development/business-buzzwords)
  sustainable: [
    "eco-friendly",
    "green",
    "ethical",
    "responsible",
    "environmentally friendly",
    "fairtrade",
    "organic",
    "renewable",
  ], //[](https://www.workspace.co.uk/content-hub/business-insight/glossary-of-business-terminology)
  local: [
    "community",
    "regional",
    "nearby",
    "neighborhood",
    "hyperlocal",
    "homegrown",
    "area-based",
  ], //[](https://www.indeed.com/career-advice/career-development/business-buzzwords)
  luxury: [
    "premium",
    "high-end",
    "exclusive",
    "upscale",
    "elite",
    "posh",
    "lavish",
    "deluxe",
  ],
  affordable: [
    "budget",
    "cheap",
    "cost-effective",
    "economical",
    "low-cost",
    "accessible",
    "reasonable",
  ],
  family: [
    "family-friendly",
    "kid-friendly",
    "child-friendly",
    "family-oriented",
    "all-ages",
    "household",
  ],
  cozy: [
    "intimate",
    "warm",
    "inviting",
    "comfortable",
    "snug",
    "homey",
    "welcoming",
  ],
  professional: [
    "expert",
    "specialist",
    "qualified",
    "skilled",
    "experienced",
    "certified",
    "credentialed",
  ],

  // Additional Industry-Specific Terms
  realestate: [
    "property",
    "realty",
    "housing",
    "development",
    "brokerage",
    "leasing",
    "mortgage",
    "land",
  ],
  automotive: [
    "car",
    "vehicle",
    "auto",
    "dealership",
    "repair",
    "service",
    "parts",
    "mechanic",
  ],
  fashion: [
    "apparel",
    "clothing",
    "boutique",
    "design",
    "style",
    "textiles",
    "couture",
    "retail",
  ],
  legal: [
    "law",
    "attorney",
    "firm",
    "practice",
    "litigation",
    "counsel",
    "advocacy",
    "paralegal",
  ],
  fitness: [
    "gym",
    "health club",
    "workout",
    "training",
    "exercise",
    "wellness",
    "coaching",
    "personal trainer",
  ],
  tourism: [
    "travel",
    "tour",
    "agency",
    "hospitality",
    "excursion",
    "vacation",
    "sightseeing",
    "adventure",
  ],
  energy: [
    "power",
    "utilities",
    "renewable",
    "solar",
    "wind",
    "oil",
    "gas",
    "electricity",
  ], //[](https://www.workspace.co.uk/content-hub/business-insight/glossary-of-business-terminology)
  government: [
    "public sector",
    "administration",
    "agency",
    "department",
    "municipal",
    "authority",
    "council",
    "governance",
  ], // From your categories
  emergency: [
    "urgent care",
    "fire",
    "police",
    "ambulance",
    "rescue",
    "crisis",
    "response",
    "safety",
  ], // From your categories
}